### ISSUE TITLE
Poor audio experience in Safari

### ISSUE THREAD

**Issue by JWGmeligMeyling** [MoodCat/MoodCat.me-Frontend#113]
Moodcat is currently unusable in Safari, because music constantly stops playing (synchronization) and  mostly doesn't start automatically (requires an additional howler.play call)

**Comment by JWGmeligMeyling** [comment]
I think this is related to #87

**Comment by JeremybellEU** [comment]
Probably fixed in #132 right?

**Comment by JWGmeligMeyling** [comment]
Yes!
