### ISSUE TITLE
Current time in song, doesn't work in classify game

### ISSUE THREAD

**Issue by Azkle** [MoodCat/MoodCat.me-Frontend#114]
I just see mostly 0:00.
For some songs it works and for some it just jumps every few seconds.

Does audio work: Yes
Does it play from and to the expected time: It starts at 0:00. Can't see the endtime and duration of the song, so not sure. But think that works.
Does it correctly skip? Had no skipping for the classify game, yet.
Are the time indication correct (timestamps above): No
Is the meta data correct: Yes, but not that good visible. Only on the classy home page, visible.

**Comment by JWGmeligMeyling** [comment]
We have very many audio issues at the moment. If we have the ambition to focus this, we should be very descriptive with our issues:
* Does audio work?
* Does it play from and to the expected time?
* Does it correctly skip?
* Are the time indication correct (timestamps above)
* Is the meta data correct

**Comment by JWGmeligMeyling** [comment]
By the way can you create an issue for the 00:00 problem in rooms as well? Or is this fixed?

**Comment by Azkle** [comment]
Will do, added the extra info to the first post.

**Comment by JWGmeligMeyling** [comment]
Thanks for the info. These sound issues freak me out haha

**Comment by Azkle** [comment]
The bar updates with interaction on the page.
