### ISSUE TITLE
it's not clear that the top room is the best fit. Maybe introduce some help graphic to enhance UX

### ISSUE THREAD

**Issue by GijsWeterings** [MoodCat/MoodCat.me-Frontend#119]

**Comment by JWGmeligMeyling** [comment]
Does the user have to know this? This might be very related to our "algorithm". But the user just wants a matching room, and it's our priority to make this as easily as possible. But I think its most importantly that the user thinks: "wow this is a good room suggestion" . We all know there wont be any good at the fifth page of Google results, but they never told us :wink:

**Comment by Azkle** [comment]
Maybe we then need to have more rooms then.
With 10 rooms the 10 room is complete opposite. 
So, then this is very important.

**Comment by JWGmeligMeyling** [comment]
Yes, we should have way more rooms. Also because simply all songs will be rejected if a user joins any other room than the first one... #105

**Comment by GijsWeterings** [comment]
I did see Mitchell pick a random room from the list, not just the top one... Let's do this issue last, IF we have time

**Comment by JWGmeligMeyling** [comment]
Yea well I think this is also related to the fact that he expect our suggestions to be good, which they aren't ;)

**Comment by JeremybellEU** [comment]
I don't think we should emphasize this more. More rooms will likely fix the issue, but we don't want to limit users in their choice for a room. Therefore I would say let's keep it like it is.
