### ISSUE TITLE
Color Send button in chat different from input field

### ISSUE THREAD

**Issue by GijsWeterings** [MoodCat/MoodCat.me-Frontend#120]

**Comment by JWGmeligMeyling** [comment]
You can just hit enter right?

**Comment by GijsWeterings** [comment]
yea but that might not be obvious for everyone

**Comment by JWGmeligMeyling** [comment]
Just checking. I think this can be useful. And easy fix <3

**Comment by GijsWeterings** [comment]
hardest part here was choosing a color :P went for a translucent green. grey/white didn't work out nice.
