### ISSUE TITLE
Update Room API calls front end

### ISSUE THREAD

**Issue by JWGmeligMeyling** [MoodCat/MoodCat.me-Frontend#14]

**Comment by JeremybellEU** [comment]
I am unable to run the frontend Angular application. First of all `npm install` or `sudo npm install` will throw permission errors randomly after about 5 minutes. Even chowning myself does not fix it. When installing various components myself, grunt is unable to find Gruntfile.js. Yes this is in the directory and a ls shows it and yes I even downloaded grunt-cli.

I currently see no option to run this application and therefore I am unable to work on this issue. HALP
