### ISSUE TITLE
When sound is muted, next song is unmuted.

### ISSUE THREAD

**Issue by maartentbm** [MoodCat/MoodCat.me-Frontend#143]
The mute button is still in "mute mode" while the next song is playing though.

**Comment by JeremybellEU** [comment]
"When you are listning to a song in a room, and mute it, when the next song comes on there will be audio again. The mute button will still show it is muted.

When you press the mute button a again it will show un-muted and the audio will continue. When you click the mute button again it will be muted and the button shows as muted."

Reported again by user.
