### ISSUE TITLE
When without being in a room selecting the mute button will show the up/down-vote buttons.

### ISSUE THREAD

**Issue by jeroen1322** [MoodCat/MoodCat.me-Frontend#148]
When you are not in a room, the up/down-vote buttons are not visible. But when you click the mute button, they are shown and clickable. When this occurs the mute-button is also broken. When you play a song after showing the up/down-vote buttons trough the mute button, the button doesn't work.

**Comment by JWGmeligMeyling** [comment]
Wow ... strange issue.

**Comment by JeremybellEU** [comment]
Can be fixed together with https://github.com/MoodCat/MoodCat.me-Frontend/issues/128
