### ISSUE TITLE
When having a song muted, it will be un-muted when the next song comes on.

### ISSUE THREAD

**Issue by jeroen1322** [MoodCat/MoodCat.me-Frontend#150]
When you are listning to a song in a room, and mute it, when the next song comes on there will be audio again. The mute button will still show it is muted. 

When you press the mute button a again it will show un-muted and the audio will continue. When you click the mute button again it will be muted and the button shows as muted.

**Comment by JeremybellEU** [comment]
Duplicate of #143

**Comment by JWGmeligMeyling** [comment]
Thanks for notifying us!
