### ISSUE TITLE
Implement V/A emoticons

### ISSUE THREAD

**Issue by GijsWeterings** [MoodCat/MoodCat.me-Frontend#18]
After our talk with Cynthia, we were encouraged to convert the thumbs up/down system into a valence arousal SAM (Self Assesment Manikin) used in philosophy. These should give a better measure of what the user thinks of a song in a room. 

Source paper: “Measuring emotion: the self assessment manikin and the semantic differential" - Bradley et al 1994

**Comment by Jaapp-** [comment]
This has already been covered by #57.
