### ISSUE TITLE
Synchronize the music with the room

### ISSUE THREAD

**Issue by Azkle** [MoodCat/MoodCat.me-Frontend#39]

**Comment by Azkle** [comment]
I'm stuck on a stupid bug, not sure how to fix it.

**Comment by JWGmeligMeyling** [comment]
Please describe the bug so that others can look into it.

**Comment by Azkle** [comment]
I tried to look into this with @GijsWeterings, but no succes so far.

It's setting the currentTime from ng-audio, that gives a non-finite double and resets itself randomly.
It gives a error on setProgress.

When setting setProgress instead of currentTime it gives undefined, before randomly resetting.
