### ISSUE TITLE
When selecting a room, the background goes gray

### ISSUE THREAD

**Issue by TimvdLippe** [MoodCat/MoodCat.me-Frontend#41]
When I select a mood which is a different mood than I previously had selected, the background goes gray for 1 second and then goes back to the original image.

It appears that the CSS trigger on state change causes this behaviour.

**Comment by JeremybellEU** [comment]
We might be able to use [onEnter](https://github.com/angular-ui/ui-router/wiki#onenter-and-onexit-callbacks) This would also fix the multiple mood selection together 1 background.

**Comment by JWGmeligMeyling** [comment]
Another problem is that because we don't send the mood for a room, the wallpaper won't appear if you enter the page on the room.

**Comment by JeremybellEU** [comment]
http://stackoverflow.com/q/13781685/2761676 maybe helps with the ng-style

**Comment by JWGmeligMeyling** [comment]
Is this still the case?

**Comment by JeremybellEU** [comment]
Yes this is still happening.
