### ISSUE TITLE
Fix outstanding issues / flaws frontend and backend

### ISSUE THREAD

**Issue by Azkle** [MoodCat/MoodCat.me-Frontend#66]

**Comment by Azkle** [comment]
I think an outstanding issue is that the wrong endpoint is called when the classify game is used. We need to use /classifygame .

**Comment by Azkle** [comment]
![image](https://cloud.githubusercontent.com/assets/5946438/8159981/179764c2-136c-11e5-808d-f2ca82c0541c.png)
I get this pop-up whilst trying to login with soundcloud. 
I click on login and then I get this instead of the normal pop-up.

**Comment by JWGmeligMeyling** [comment]
The token is exchanged with the token for the live system. Replace the soundcloud token back if you want to use it locally.

**Comment by JWGmeligMeyling** [comment]
Increased the story points as I have worked for 10 hours on this yesterday and another few hours today.
