### ISSUE TITLE
Change the background depending on the mood

### ISSUE THREAD

**Issue by JeremybellEU** [MoodCat/MoodCat.me-Frontend#7]
The current background is static, it would be nice if the background could change when a mood is selected.

This would make the mood more visual and could influence the user experience.

**Comment by Jaapp-** [comment]
Random background images per mood can be requested through http://188.166.92.29/mood-bg/<mood>/ where <mood> is one of these moods:
bored/  calm/  exciting/  happy/  nervous/  peaceful/  pleasing/  relaxing/  sad/  sleepy/
To add more backgrounds, they can be added in their respective directories on the server.
