### ISSUE TITLE
Fix vagrant setup on Windows

### ISSUE THREAD

**Issue by JeremybellEU** [MoodCat/MoodCat.me-Frontend#8]
It appears that on Windows the vagrant setup does not work. See #6 for screenshots.

**Comment by JeremybellEU** [comment]
Vagrant succesfully installed, however now 'grunt serve' now throws an error because coffee-script is not installed.

**Comment by JWGmeligMeyling** [comment]
npm install && bower install?

**Comment by JeremybellEU** [comment]
`bower install` failed on the very last git repository (aria), but @GijsWeterings supplied me the bower components. I will run `npm install` which hopefully fixes the issues.

**Comment by JWGmeligMeyling** [comment]
We should put this issue on hold for a while I think, were really losing time on this one. Maybe just install Node and Gem for now. (and compass and bower with that)

**Comment by JeremybellEU** [comment]
Most issues seem to be fixed, but if it ain't working we still have 3 other computers that are able to run it. I think we can close or put back on the backlog, as it has low priority now.

**Comment by JeremybellEU** [comment]
Both me and @Azkle are able to develop frontend on our laptops now.

**Comment by JWGmeligMeyling** [comment]
I still have some doubts if this is clear enough for SIG / our deliveries though.
