### ISSUE TITLE
Soundcloud Login fails in production

### ISSUE THREAD

**Issue by JWGmeligMeyling** [MoodCat/MoodCat.me-Frontend#80]
Using the production Soundcloud API ID and host name (http://moodcat.me) the authentication fails. This is because SC.accessToken() seems to return `null` after logging in to SoundCloud's services.

SoundCloud API usage in https://github.com/MoodCat/MoodCat.me-Frontend/blob/master/app/scripts/services/audio/soundCloudService.js : 
```js
      SC.initialize({
        client_id: soundCloudKey,
        redirect_uri: window.location.origin,
        access_token: $cookieStore.get('scAuth'),
        scope: 'non-expiring'
      });

      this.loginUsingSoundcloud = function loginUsingSoundcloud() {
        var deferred = $q.defer();

        SC.connect(function() {
          deferred.resolve();
          var accessToken = SC.accessToken();
          $cookieStore.put('scAuth', accessToken);
          $rootScope.loggedIn = true;
          $rootScope.$broadcast('soundcloud-login');
        });

        return deferred.promise;
      };

```

This is related to https://github.com/soundcloud/soundcloud-javascript/issues/19
A Stackoverflow question exists on http://stackoverflow.com/questions/30767228/soundcloud-sdk-not-receiving-token-callback-in-production-environments-in-safar

**Comment by JeremybellEU** [comment]
This has been fixed by #82.
