### ISSUE TITLE
Bug: Sometimes the music falls silent while counters keep running 

### ISSUE THREAD

**Issue by JWGmeligMeyling** [MoodCat/MoodCat.me-Frontend#87]

**Comment by JWGmeligMeyling** [comment]
We should check if this still happens https://github.com/MoodCat/MoodCat.me-Frontend/pull/97

**Comment by Azkle** [comment]
This is not happening in Chrome anymore. But replaced by #115

**Comment by JWGmeligMeyling** [comment]
Ok we might close it then.
