### ISSUE TITLE
Improve state transition animations

### ISSUE THREAD

**Issue by TimvdLippe** [MoodCat/MoodCat.me-Frontend#93]
The current state transitions are not fluent and sometimes cause non-smooth behaviour on the client. For example the lists are rendered just after the page is transitioned, causing elements to place differently (footer for example).

**Comment by JWGmeligMeyling** [comment]
The data is fetched async. The UI is not blocked while you are waiting on data. Only the state transition is delayed till the data is fetched. This behaviour is preferred. We could decide to show a preloader. But the loading is async.

**Comment by JeremybellEU** [comment]
Reopened issue with new title, as issue still exists, but different matter.

**Comment by JWGmeligMeyling** [comment]
Related to #41
